Fix package lock
Installing v1 tool poetry v1.1.13

Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/argparse.py", line 89, in <module>
    import re as _re
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/re.py", line 127, in <module>
    import functools
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/functools.py", line 18, in <module>
    from collections import namedtuple
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/collections/__init__.py", line 36, in <module>
    from operator import eq as _eq
  File "/mnt/renovate/gh/camptocamp/operator-shared-config-manager/docker/operator.py", line 3, in <module>
    import asyncio
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/traceback.py", line 5, in <module>
    import linecache
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/linecache.py", line 11, in <module>
    import tokenize
  File "/opt/buildpack/tools/python/3.10.5/lib/python3.10/tokenize.py", line 38, in <module>
    cookie_re = re.compile(r'^[ \t\f]*#.*?coding[:=][ \t]*([-\w.]+)', re.ASCII)
AttributeError: partially initialized module 're' has no attribute 'compile' (most likely due to a circular import)